Repository Eat-Local/eat-local-fe, pull requests merged in 2022-12, with the labels that each got.

#2 add config file
  .circleci/config.yml
Labels: enhancement

#3 Add lockfile
  package-lock.json
Labels: enhancement

#4 Feature/circleci setup
  .circleci/config.yml
  cypress.config.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
Labels: enhancement, FE

#5 Install packages for graphql and apollo
  package-lock.json
  package.json
Labels: enhancement, FE

#19 Favorites
  cypress/e2e/favorites-spec.cy.js
  src/components/App/App.js
  src/components/FavoritesPage/FavoritesPage.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
Labels: enhancement, FE

#21 Feature/landingpage component
  src/components/App/App.js
  src/components/LandingPage/LandingPage.css
  src/components/LandingPage/LandingPage.js
  src/components/ResultCard/ResultCard.js
Labels: enhancement, FE

#34 Feat/fetch data
  src/components/App/App.css
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/LandingPage/LandingPage.css
  src/components/LandingPage/LandingPage.js
  src/components/Nav/Nav.js
  src/components/ResultCard/ResultCard.css
  src/components/ResultsPage/ResultsPage.css
  src/components/ResultsPage/ResultsPage.js
  src/components/Search/Search.js
  src/index.css
Labels: enhancement, FE

#35 Add router functionality, data rendering
  src/components/App/App.js
  src/components/Nav/Nav.js
  src/components/ResultCard/ResultCard.js
  src/components/ResultsPage/ResultsPage.js
  src/components/Search/Search.js
  src/components/SingleResultPage/SingleResultPage.js
Labels: enhancement, FE, MVP

#36 Feat/login
  src/components/App/App.js
  src/components/Login/Login.css
  src/components/Login/Login.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/ResultsPage/ResultsPage.css
Labels: enhancement, FE, MVP

#37 Trying map
  .gitignore
  package-lock.json
  package.json
  src/components/SingleResultPage/SingleResultPage.css
  src/components/SingleResultPage/SingleResultPage.js
Labels: FE, extension

#41 Feature/user functionality
  src/components/App/App.js
  src/components/Login/Login.js
  src/components/Nav/Nav.js
  src/index.js
Labels: FE, MVP

#42 Cleanup
  src/components/App/App.js
  src/components/FavoritesPage/FavoritesPage.css
  src/components/FavoritesPage/FavoritesPage.js
  src/components/Login/Login.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/SingleResultPage/SingleResultPage.css
  src/components/SingleResultPage/SingleResultPage.js
Labels: enhancement, FE, MVP

#51 Cypress/favorites page testing
  cypress/e2e/favorites-spec.cy.js
  cypress/e2e/landing-spec.cy.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/createFav.json
  cypress/fixtures/deleteFav.json
  cypress/fixtures/userQuery.json
  cypress/fixtures/userQueryNoFavs.json
  src/components/FavoritesPage/FavoritesPage.js
  src/components/Login/Login.js
  src/components/ResultCard/ResultCard.js
Labels: enhancement, FE, MVP, bugfix

#52 Styling footer
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/ResultCard/ResultCard.css
  src/components/Search/Search.css
  src/index.css
Labels: enhancement, FE

#53 Cypress/results page testing
  cypress/e2e/landing-spec.cy.js
  cypress/e2e/results-spec.cy.js
  src/components/ResultsPage/ResultsPage.js
Labels: FE, MVP

#54 Correct accessibility audit to 100
  src/components/ResultCard/ResultCard.css
  src/components/Search/Search.js
Labels: enhancement, FE

#56 Clean up
  cypress/e2e/favorites-spec.cy.js
  cypress/e2e/single-results-spec.cy.js
  cypress/fixtures/example.json
  src/assets/mock-data.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/Login/Login.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/ResultCard/ResultCard.css
  src/components/ResultsPage/ResultsPage.css
  src/components/SingleResultPage/SingleResultPage.js
  src/index.css
Labels: enhancement, FE

#61 Remove only from favorite spec test
  cypress/e2e/favorites-spec.cy.js
Labels: bugfix
